name: asset_generator
description: A Dart package that generates code for asset paths and pre-caches images, simplifying asset management in Flutter projects.
homepage: https://github.com/OmarMahmoud-alam/asset_generator.git
repository: https://github.com/OmarMahmoud-alam/asset_generator.git
version: 1.3.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.0
  dart_style: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  
executables:
  generate:


asset_generator:
  images:
    - assets/images/achievimage/

  icons:
    - assets/images/bottomnavigateicon/Alert/
  output_dir: lib/omar/generated_images.dart
  class_name: Kii